name: admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  flutter_bloc: ^8.0.1
  flutter_admin_scaffold: ^1.0.0
  http: ^1.2.2  # Hoặc phiên bản mới nhất
  fl_chart: ^0.40.0


  # Thêm các thư viện khác tùy theo nhu cầu của bạn


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/files/
    - assets/images/
    - assets/icons/
    - assets/images/nutri/

